### ISSUE TITLE
Change `.title-box11` style center

### ISSUE THREAD

**Issue by toshikisugiyama** [andy09292004/isara#8]
Change [`css/isr-styles.css`](https://github.com/andy09292004/isara/blob/726738236a3c33ba02a5e749cb39be755b8475b1/css/isr-styles.css#L640-L650) to below.

```css
 .title-box11 {
  position: absolute;
  display: block;
  padding: 0 .5em;
  left: 50%;
  transform: translateX(-50%);
  top: -15px;
  font-weight: bold;
  background-color:  rgb(252, 203, 112);
  color: #555555; /* タイトル文字色 */
 }
```

It will make the style like below.

![.title-box11](https://i.gyazo.com/7ff81376bbafb6ab71bb4c2aab3df1c0.png)
